defaults:
  - _self_
  - task@_global_: cartpole-v0 # just for kicks for now
  - alg@_global_: bc

# general environment things (all specified later)
obs_shape: ???
action_shape: ???
continuous: ???
img_input: ???

# optimization
seed: 100
optim: adam
lr: 3e-4
clip_grad_norm: false
max_grad_norm: 0.5

# general neural net things (common for all algos)
activation: relu
activate_final: true

softplus: false
min_std: 0.1

# conv args (common for all algos)
channels: [32, 32, 32]
kernels: [5, 5, 5]
strides: [3, 1, 1]

# mlp args (common for all algos)
hidden_sizes: [256, 256]
use_ln: false

hydra:
  run:
    dir: ./local_runs/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}